### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by data-ant** [Nilabhra/RNTN#1]
Excuse me ?
I'm wondering why the results didn't meet the level in Socher's paper?
I'm a little misunderstanding for the 0.7 result..

thx!!

**Comment by Nilabhra** [comment]
Hello,

Yes, the results can be improved if you use bigger word vectors. The
current Jupyter notebook displays the performance of a model which had 30
or 50 dimensional word vectors. Otherwise the implementation is exactly the
same as described in the paper. (Best to my knowledge)

Thanks,
Nilabhra

**Comment by data-ant** [comment]
OK，It's fine！ Thanks for your information~~
I'll go on testing them and once it impoves, i'll inform you~
Good Luck!

**Comment by Nilabhra** [comment]
Sure thing. May I ask what are you building?

**Comment by Nilabhra** [comment]
I guess everything was okay on your side. Closing the issue now.
